apiVersion: apps/v1
kind: Deployment
metadata:
  name: freeapi-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: freeapi
  template:
    metadata:
      labels:
        app: freeapi
    spec:
      containers:
      - name: freeapi
        image: noscopev6/chatapi:v1
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: MONGO_MEMORY_SERVER_PORT
          value: "10000"
        - name: MONGODB_URI
          value: "mongodb+srv://aacaacd:Sacacadcac1324354l@cluster0.qvnvbno.mongodb.net"
        - name: NODE_ENV
          value: "development"
        - name: EXPRESS_SESSION_SECRET
          value: "7fdOMCFRSLD9cv1k-5n3Dz5n3DmVmVHVIg9GG_OGTUkBfLNdgZAwKDNtoCJ0X0cyqaM0ogR80-zh9kx0Mkx"
        - name: ACCESS_TOKEN_SECRET
          value: "LD9cv1kBfgRHVIg9GG_OGzh9TUkcyqgZAaM0o3DmVkx08MCFRSzMocyO3UtNdDNtoCJ0X0-5nLwK7fdO"
        - name: ACCESS_TOKEN_EXPIRY
          value: "1d"
        - name: REFRESH_TOKEN_SECRET
          value: "CMdDNtowK7fX0-5D9cv0oJ008MCFRSLHVTUkcyqgZAaIg9GG_OGzh9zMocyO3UtN1kBfLRn3DmVkxdO"
        - name: REFRESH_TOKEN_EXPIRY
          value: "10d"
        - name: CORS_ORIGIN
          value: "https://chat.net"
        - name: FREEAPI_HOST_URL
          value: "https://chat.net"
