## use this to encode password fields [echo -n "staging-db-password" | base64 ]
apiVersion: v1
kind: Secret
metadata:
  name: chat-app-secret-staging
  namespace: staging
type: Opaque
data:
  DATABASE_PASSWORD: c3RhZ2luZy1kYi1wYXNzd29yZA==  # staging-db-password


---


apiVersion: v1
kind: Secret
metadata:
  name: chat-app-secret-prod
  namespace: production
type: Opaque
data:
  DATABASE_PASSWORD: c3VwZXJzZWNyZXRwYXNzd29yZA==  # supersecretpassword
