name: Build ChatAPP

on:
  push:
    branches:
      - main
    tags:
      - 'v1.*'

jobs:

  code-scan:
    runs-on: digitalocean
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: run conatiner to scan the code review 
      run: |
        java -version
        export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
        export PATH=$JAVA_HOME/bin:$PATH
        java -version
        sonar-scanner \
          -Dsonar.projectKey=chatapp \
          -Dsonar.sources=./ \
          -Dsonar.host.url=http://localhost:9000 \
          -Dsonar.login=sqp_be4203a1a95d57a7eb61cc0fc4dc96a06ae4c935

  build-api:
    runs-on: digitalocean
    needs: code-scan  # This job will run only if 'code-scan' succeeds 

    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build Docker image
      run: docker build -t noscopev6/chatapp-b:$GITHUB_SHA .

    - name: Push Docker image
      run: docker push noscopev6/chatapp-b:$GITHUB_SHA

    - name: Push Docker image
      run: docker logout
    
  build-fronend:
    runs-on: digitalocean
    needs: build-api  # This job will run only if 'build-api' succeeds

    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build Docker image
      run: cd ./frontend/chat-app && docker build -t noscopev6/chatapp-f:$GITHUB_SHA .

    - name: Push Docker image
      run: docker push noscopev6/chatapp-f:$GITHUB_SHA

    - name: Push Docker image
      run: docker logout